# Controlplane と Workerで共通のタスク
#- debug: msg="{{ ansible_facts }}"

- name: check exisiting /etc/yum.repos.d/kubernetes.repo
  stat:
    path: "/etc/yum.repos.d/kubernetes.repo"
  register: kubernetes_repo

- name: install kubernetes.repo
  become: yes
  template:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
  when:
    - kubernetes_repo.stat.exists == false

- name: check exisiting /etc/yum.repos.d/cri-o.repo
  stat:
    path: "/etc/yum.repos.d/cri-o.repo"
  register: crio_repo

- name: install kubernetes.repo
  become: yes
  template:
    src: cri-o.repo
    dest: /etc/yum.repos.d/cri-o.repo
  when:
    - crio_repo.stat.exists == false

- name: install container-selinux cri-o kubelet kubeadm kubectl
  become: yes
  dnf:
    name:
      - container-selinux
      - cri-o
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: start crio
  become: yes
  systemd:
    name: crio
    state: started
    enabled: yes

- name: enable kubelet
  become: yes
  systemd:
    name: kubelet
    state: started
    enabled: yes

- name: disable swap
  become: yes
  command: swapoff -a

- name: modprebe br_netfilter
  become: yes
  command: modprobe br_netfilter

- name: ip fowarding setting
  become: yes
  sysctl: name="net.ipv4.ip_forward" value=1 

- name: Check if Helm GPG key exists
  stat:
    path: /etc/apt/keyrings/helm.gpg
  register: helm_gpg_key
  changed_when: false

- name:  Add Helm GPG key
  shell: curl https://baltocdn.com/helm/signing.asc | gpg --dearmor --batch --yes --output /etc/apt/keyrings/helm.gpg
  when: not helm_gpg_key.stat.exists

- name: Add Helm apt repository
  lineinfile:
    path: /etc/apt/sources.list.d/helm.list
    line: deb [signed-by=/etc/apt/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main
    create: yes
