# Common tasks for control plane and worker plane
- name: check exisiting /etc/yum.repos.d/kubernetes.repo
  stat:
    path: "/etc/yum.repos.d/kubernetes.repo"
  register: kubernetes_repo

- name: install kubernetes.repo
  become: yes
  template:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
  when:
    - kubernetes_repo.stat.exists == false

- name: check exisiting /etc/yum.repos.d/cri-o.repo
  stat:
    path: "/etc/yum.repos.d/cri-o.repo"
  register: crio_repo

- name: install kubernetes.repo
  become: yes
  template:
    src: cri-o.repo
    dest: /etc/yum.repos.d/cri-o.repo
  when:
    - crio_repo.stat.exists == false

- name: check exisiting /usr/local/bin/helm
  stat:
    path: "/usr/local/bin/helm"
  register: helm

# Ignore error because ansible cannot read the $PATH (/usr/local/bin)
- name: install helm
  become: yes
  shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  ignore_errors: yes
  when:
    - helm.stat.exists == false

- name: install container-selinux cri-o kubelet kubeadm kubectl
  become: yes
  dnf:
    name:
      - container-selinux
      - cri-o
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: start crio
  become: yes
  systemd:
    name: crio
    state: started
    enabled: yes

- name: enable kubelet
  become: yes
  systemd:
    name: kubelet
    state: started
    enabled: yes

- name: disable swap
  become: yes
  command: swapoff -a

- name: modprebe br_netfilter
  become: yes
  command: modprobe br_netfilter

- name: check exisiting /etc/modules-load.d/br_netfilter.conf
  stat:
    path: "/etc/modules-load.d/br_netfilter.conf"
  register: br_netfilter

- name: install kubernetes.repo
  become: yes
  shell: echo "br_netfilter" > /etc/modules-load.d/br_netfilter.conf
  when:
    - br_netfilter.stat.exists == false

- name: ip fowarding setting
  become: yes
  sysctl: name="net.ipv4.ip_forward" value=1
