# Controlplane のみのタスク
#- debug: msg="{{ ansible_facts }}"

## Kubeadm init が実行されているかをチェックする
- name: check exisiting /tmp/kubeadm-join.yaml
  stat:
    path: "/tmp/kubeadm-join.yaml"
  register: kubeadm_join

## Kubeadm init コマンドを実行し記録する
- name: kubeadm init
  become: yes
  command: kubeadm init --pod-network-cidr={{ flannel_cidr }}
  register: join_command
  when:
    - kubeadm_join.stat.exists == false

## kubeadm ノード用コマンドを保存
- name: create kubeadm join command
  shell: echo "join_command" ":" {{ join_command.stdout_lines[-2] }} {{ join_command.stdout_lines[-1] }} > /tmp/kubeadm-join.yaml
  when:
    - kubeadm_join.stat.exists == false