# Worker のみのタスク
#- debug: msg="{{ ansible_facts }}"

## kubeadmのJoinコマンドをコントロールプレーンからコピーし参加する
- name: Copy join command file from controlplane
  ansible.builtin.copy:
    src: /tmp/kubeadm-join.yaml
    dest: /tmp/kubeadm-join.yaml
- name: include kubeadm join token etc
  include_vars: /tmp/kubeadm-join.yaml
- name: kubeadm join
  become: yes
  command: "{{ join_command }}"  