# Only worker plane tasks
# Make dir for .kube
- name: mkdir kubeconfig
  file:
    path: /home/cloudinit/.kube
    state: directory
    owner: cloudinit
    group: cloudinit
    mode: "0755"

# Copy admin.conf from Ansible control node
- name: Copy admin.conf to user's kube config
  become: yes
  copy:
    src: /home/cloudinit/.kube/config
    dest: /home/cloudinit/.kube/config
    owner: cloudinit
    group: cloudinit
    mode: 0600

# Check if node is part of cluster
- name: Check if node is part of cluster
  shell: kubectl get nodes | grep -q {{ ansible_facts['hostname'] }}
  register: node_status
  changed_when: false
  failed_when: node_status.rc not in [0,1]

# Copy join commmand file from control plane
- name: Copy join command file from control plane
  copy:
    src: /tmp/kubeadm-join.yaml
    dest: /tmp/kubeadm-join.yaml
  when: node_status.rc != 0

- name: include kubeadm join token etc
  include_vars: /tmp/kubeadm-join.yaml
  when: node_status.rc != 0

- name: kubeadm join
  become: yes
  command: "{{ join_command }}"
  when: node_status.rc != 0
