# Worker のみのタスク
#- debug: msg="{{ ansible_facts }}"
- name: Wait 600 seconds for target connection to become reachable/usable
  ansible.builtin.wait_for_connection:

- name: mkdir kubeconfig
  file:
    path: /home/cloudinit/.kube
    state: directory
    owner: cloudinit
    group: cloudinit
    mode: "0755"

- name: Copy admin.conf to user's kube config
  become: yes
  copy:
    src: /home/cloudinit/.kube/config
    dest: /home/cloudinit/.kube/config
    owner: cloudinit
    group: cloudinit
    mode: 0600

- name: Check if node is part of cluster
  shell: kubectl get nodes | grep -q {{ ansible_facts['hostname'] }}
  register: node_status
  changed_when: false
  failed_when: node_status.rc not in [0,1]

# kubeadmのJoinコマンドをコントロールプレーンからコピーし参加する
- name: Copy join command file from controlplane
  copy:
    src: /tmp/kubeadm-join.yaml
    dest: /tmp/kubeadm-join.yaml
  when: node_status.rc != 0

- name: include kubeadm join token etc
  include_vars: /tmp/kubeadm-join.yaml
  when: node_status.rc != 0

- name: kubeadm join
  become: yes
  command: "{{ join_command }}"
  when: node_status.rc != 0
