# Worker のみのタスク
#- debug: msg="{{ ansible_facts }}"

## kubeadmのJoinコマンドをコントロールプレーンからコピーする
- name: Copy join command file from controlplane
  ansible.builtin.copy:
    remote_src: true
    src: /tmp/kubeadm-join.yaml
    dest: /tmp/kubeadm-join.yaml
