---
- name: 01-ssh-keygen
  hosts: k8s-master
  roles:
    - 01-ssh-keygen

- name: 02-setup-sshd-config
  hosts: k8s-servers
  roles:
    - 02-setup-sshd-config

- name: 11-kube-install
  hosts: k8s-servers-with-key
  roles:
    - 11-kube-install

- name: 12-kube-init
  hosts: k8s-master-with-key
  roles:
    - 12-kube-init

- name: 13-kube-join
  hosts: k8s-node-with-key
  roles:
    - 13-kube-join

- name: 14-kube-config
  hosts: k8s-master-with-key
  roles:
    - 14-kube-config
