- name: Copy public key
  become: yes
  copy:
    src: /home/cloudinit/.ssh/id_ed25519.pub
    dest: /home/cloudinit/.ssh/id_ed25519.pub
    owner: cloudinit
    group: cloudinit
    mode: 0600

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: cloudinit
    state: present
    key: "{{ lookup('file', '/home/cloudinit/.ssh/id_ed25519.pub') }}"

- name: Configure sshd
  become: yes
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{item.key}}"
    line: "{{item.key}} {{item.value}}"
    state: present
  loop:
    - { key: "PermitRootLogin", value: "no" }
    - { key: "PasswordAuthentication", value: "no" }
  notify:
    - require_reload_sshd
